# Generated by Django 3.2.6 on 2021-08-15 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(max_length=255)),
                ('year_released', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message="Album year must be entered in the format: 'XXXX'.", regex='^\\d{4}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
